apiVersion: v1
kind: ConfigMap
metadata:
  name: tejo-config
  namespace: tejo-beauty
data:
  # Database
  DATABASE_URL: "postgresql://tejo:tejopass123@tejo-postgres:5432/tejobeauty"
  
  # Redis
  REDIS_URL: "redis://tejo-redis:6379"
  
  # Meilisearch
  MEILISEARCH_URL: "http://tejo-meilisearch:7700"
  MEILISEARCH_KEY: "tejoMasterKey123"
  
  # API
  NODE_ENV: "development"
  PORT: "4000"
  
  # Frontend
  NEXT_PUBLIC_API_URL: "http://localhost:4000"
  NEXT_PUBLIC_SITE_URL: "http://localhost:3000"
  
  # Worker
  API_BASE_URL: "http://tejo-api:4000"
  MEILI_URL: "http://tejo-meilisearch:7700"
  MEILI_MASTER_KEY: "tejoMasterKey123"
